# static/admin/config.yml
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: /img

collections:
  - name: "movies"
    label: "Movies"
    folder: "content/movies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tagline", name: "tagline", widget: "string"}
      - {label: "Release Date", name: "releaseDate", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "SEO Description", name: "seoDescription", widget: "text"}
      - {label: "Director", name: "director", widget: "string"}
      - {label: "Producer", name: "producer", widget: "string"}
      - {label: "Production Company", name: "productionCompany", widget: "string"}
      - {label: "Poster Image", name: "posterImage", widget: "image"}
      - {label: "Background Image", name: "backgroundImage", widget: "image"}
      - {label: "Trailer URL", name: "trailerUrl", widget: "string", required: false}
      - label: "Cast"
        name: "cast"
        widget: "list"
        fields:
          - {label: "Actor Name", name: "name", widget: "string"}
          - {label: "Character Name", name: "character", widget: "string"}
      - label: "Genres"
        name: "genres"
        widget: "select"
        multiple: true
        options: ["Drama", "Documentary", "Comedy", "Action", "Thriller", "Romance", "Sci-Fi", "Horror"]
      - {label: "Duration (in minutes)", name: "duration", widget: "number"}
      - {label: "Language", name: "language", widget: "string"}
      - label: "Social Media Links"
        name: "socialLinks"
        widget: "object"
        fields:
          - {label: "Twitter", name: "twitter", widget: "string", required: false}
          - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'distributors'
    label: 'Distributors'
    folder: 'content/distributors'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Access Level', name: 'accessLevel', widget: 'select', options: ['basic', 'premium', 'full'] }

  - name: 'materials'
    label: 'Materials'
    folder: 'content/materials'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Access Level', name: 'accessLevel', widget: 'select', options: ['basic', 'premium', 'full'] }

  - name: "locations"
    label: "Locations"
    folder: "content/locations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Country", name: "country", widget: "string"}
      - {label: "Region/State", name: "region", widget: "string"}
      - {label: "City", name: "city", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Climate", name: "climate", widget: "string"}
      - {label: "Local Culture", name: "localCulture", widget: "text"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}

  - name: "houses"
    label: "Houses"
    folder: "content/houses"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "relation", collection: "locations", search_fields: ["name", "country", "region", "city"], value_field: "{{slug}}", display_fields: ["name", "country", "region", "city"]}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Price", name: "price", widget: "number", value_type: "float"}
      - {label: "Currency", name: "currency", widget: "select", options: ["USD", "EUR", "GBP"]}
      - {label: "Number of Bedrooms", name: "bedrooms", widget: "number", value_type: "int"}
      - {label: "Number of Bathrooms", name: "bathrooms", widget: "number", value_type: "float"}
      - {label: "Total Area (sq m)", name: "totalArea", widget: "number", value_type: "float"}
      - {label: "Land Area (sq m)", name: "landArea", widget: "number", value_type: "float"}
      - {label: "Year Built", name: "yearBuilt", widget: "number", value_type: "int"}
      - {label: "Architecture Style", name: "architectureStyle", widget: "string"}
      - label: "Restoration State"
        name: "restorationState"
        widget: "select"
        options:
          - {label: "Original", value: "original"}
          - {label: "Partially Restored", value: "partiallyRestored"}
          - {label: "Fully Restored", value: "fullyRestored"}
          - {label: "Needs Restoration", value: "needsRestoration"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Features"
        name: "features"
        widget: "list"
        field: {label: Feature, name: feature, widget: string}
      - label: "Photos"
        name: "photos"
        widget: "list"
        summary: "{{fields.caption}}"
        field: {label: Image, name: image, widget: image}
        fields:
          - {label: Caption, name: caption, widget: string}
      - label: "Floor Plans"
        name: "floorPlans"
        widget: "list"
        summary: "{{fields.name}}"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - {label: "Virtual Tour URL", name: "virtualTourUrl", widget: "string", required: false}
      - label: "Nearby Amenities"
        name: "nearbyAmenities"
        widget: "list"
        field: {label: Amenity, name: amenity, widget: string}
      - {label: "Energy Efficiency Rating", name: "energyEfficiencyRating", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}